export const estates = [
    {name: 'Treasure Park & Gardens'},
    {name: "CapeTown Estate"},
    {name: "Cranberry"},
    {name: "Pictorial Gardens"},
    {name: "Rehoboth Park And Gardens Phase 2 Extension 2"},
    {name: "Emirates Park & Gardens, Badagry"},
    {name: "Rehoboth Park & Gardens Phase 2(Ocean View Estate)"},
    {name: "Eko City"},
    {name: "Emirates Park & Gardens Phase 2, Badagry"},
    {name: "Washington Park & Gardens"},
    {name: "Imperial Park And Gardens(The Sugarland Estate)"},
    {name: "Grandview Park & Gardens Phase 1 Extension"},
    {name: "Sunrise Park & Gardens"},
    {name: "Winter Park & Gardens"},
    {name: "Chicago Park & Gardens"},
    {name: "Houston Park & Gardens"},
    {name: "Treasure Park & Gardens Phase 5 (CITY OF GOD)"},
    {name: "Treasure Park & Gardens (The Gold Estate)"},
    {name: "Treasure Park & Gardens Phase 4 (Jerusalem Extension)"},
    {name: "Treasure Park And Gardens Phase1 Extension(Golf Estate)"},
    {name: "Glass House Estate"},
    {name: "Town Park & Gardens Phase 1 Emuren Imota"},
    {name: "Town Park & Gardens Phase 1 Extension Emuren Imota"},
    {name: "Grandview Park & Gardens Phase1"},
    {name: "Southgate Park & Gardens"},
    {name: "Grandview Park & Gardens China Town"},
    {name: "Treasure Park & Gardens Phase 2 Extension (Downtown Parks And Garden)"},
    {name: "Treasure Park & Gardens Phase 1"},
    {name: "Treasure Park & Gardens Phase 3(Cape Town)"},
    {name: "Central Park & Gardens 4, Gwagalada"},
    {name: "Central Park & Gardens 3, Bamishi Kuje"},
    {name: "Central Park & Gardens Phase 2 Giri Gwagalada"},
    {name: "West Park & Gardens Phase 1 Extension, Oleyo"},
    {name: "City Park & Gardens ,Phase 2,Asejire"},
    {name: "Rosewood Park & Gardens"},
    {name: "City Park & Gardens, Phase 1(Palm City), Asejire"},
    {name: "London Park & Gardens"},
    {name: "West Park And Garden (Asepa-Ayegun Paradise City)"},
    {name: "Moscow Park & Gardens"},
    {name: "Paris Park & Gardens"},
    {name: "Buckingham Park & Gardens"},
    {name: "New York Park And Gardens"},
    {name: "Manhattan Park & Gardens"},
    {name: "Manhattan Park & Gardens Phase 2"},
    {name: "Emirate Park & Gardens Phase 1 (The Eden)"},
    {name: "Emirate Park & Gardens Phase 2 (Paradise Estate)"},
]