export const estates = [
    {id: 1, name: "Cranberry"},
    {id: 2, name: "Pictorial Gardens"},
    {id: 3, name: "Rehoboth Park And Gardens Phase 2 Extension 2"},
    {id: 4, name: "Emirates Park & Gardens, Badagry"},
    {id: 5, name: "Rehoboth Park & Gardens Phase 2(Ocean View Estate)"},
    {id: 6, name: "Eko City"},
    {id: 7, name: "Emirates Park & Gardens Phase 2, Badagry"},
    {id: 8, name: "Washington Park & Gardens"},
    {id: 9, name: "Imperial Park And Gardens(The Sugarland Estate)"},
    {id: 10, name: "Grandview Park & Gardens Phase 1 Extension"},
    {id: 11, name: "Sunrise Park & Gardens"},
    {id: 12, name: "Winter Park & Gardens"},
    {id: 13, name: "Chicago Park & Gardens"},
    {id: 14, name: "Houston Park & Gardens"},
    {id: 15, name: "Treasure Park & Gardens Phase 5 (CITY OF GOD)"},
    {id: 16, name: "Treasure Park & Gardens (The Gold Estate)"},
    {id: 17, name: "Treasure Park & Gardens Phase 4 (Jerusalem Extension)"},
    {id: 18, name: "Treasure Park And Gardens Phase1 Extension(Golf Estate)"},
    {id: 19, name: "Glass House Estate"},
    {id: 20, name: "Town Park & Gardens Phase 1 Emuren Imota"},
    {id: 21, name: "Town Park & Gardens Phase 1 Extension Emuren Imota"},
    {id: 22, name: "Grandview Park & Gardens Phase1"},
    {id: 23, name: "Southgate Park & Gardens"},
    {id: 24, name: "Grandview Park & Gardens China Town"},
    {id: 25, name: "Treasure Park & Gardens Phase 2 Extension (Downtown Parks And Garden)"},
    {id: 26, name: "Treasure Park & Gardens Phase 1"},
    {id: 27, name: "Treasure Park & Gardens Phase 3(Cape Town)"},
    {id: 28, name: "Central Park & Gardens 4, Gwagalada"},
    {id: 29, name: "Central Park & Gardens 3, Bamishi Kuje"},
    {id: 30, name: "Central Park & Gardens Phase 2 Giri Gwagalada"},
    {id: 31, name: "West Park & Gardens Phase 1 Extension, Oleyo"},
    {id: 32, name: "City Park & Gardens ,Phase 2,Asejire"},
    {id: 33, name: "Rosewood Park & Gardens"},
    {id: 34, name: "City Park & Gardens, Phase 1(Palm City), Asejire"},
    {id: 35, name: "London Park & Gardens"},
    {id: 36, name: "West Park And Garden (Asepa-Ayegun Paradise City)"},
    {id: 37, name: "Moscow Park & Gardens"},
    {id: 38, name: "Paris Park & Gardens"},
    {id: 39, name: "Buckingham Park & Gardens"},
    {id: 40, name: "New York Park And Gardens"},
    {id: 41, name: "Manhattan Park & Gardens"},
    {id: 42, name: "Manhattan Park & Gardens Phase 2"},
    {id: 43, name: "Emirate Park & Gardens Phase 1 (The Eden)"},
    {id: 44, name: "Emirate Park & Gardens Phase 2 (Paradise Estate)"},
]